version: "3.1"

services:
  mongodb:
    image: mongo:latest
    container_name: rubo-mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080

volumes:
  mongodb_data: