package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"net/http"

	"github.com/Lucas-Linhar3s/Rubo/modules/graphql/generated"
	"github.com/Lucas-Linhar3s/Rubo/modules/graphql/model"
	"github.com/Lucas-Linhar3s/Rubo/pkg/http/response/v1"
)

// CreateNew is the resolver for the createNew field.
func (r *mutationResolver) CreateNew(ctx context.Context, new model.NewInput) (*model.New, error) {
	err := fmt.Errorf("not implemented: CreateNew - new")
	v1.GraphError(ctx, http.StatusInternalServerError, "Erro no resolver", err)
	return nil, err
}

// New is the resolver for the new field.
func (r *queryResolver) New(ctx context.Context, id string) (*model.New, error) {
	panic(fmt.Errorf("not implemented: New - new"))
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
