// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type LoginUserInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type New struct {
	ID string `json:"id"`
}

type NewInput struct {
	ID string `json:"id"`
}

type Query struct {
}

type RegisterUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SessionOut struct {
	UserID        string `json:"userID"`
	AccessToken   string `json:"accessToken"`
	DataExpiracao string `json:"dataExpiracao"`
}

type User struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Email     string  `json:"email"`
	Password  *string `json:"password,omitempty"`
	Role      *string `json:"role,omitempty"`
	CreatedAt string  `json:"createdAt"`
	UpdatedAt string  `json:"updatedAt"`
}
